import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

export interface BillOfSaleData {
  purchaseId: string;
  date: string; // YYYY-MM-DD
  vehicle: {
    year: number;
    make: string;
    model: string;
    trim: string | null;
    vin: string | null;
    miles: number;
    color: string | null;
  };
  seller: { legalName: string; address: string; phone: string; email: string };
  buyer: { legalName: string; address: string; phone: string; email: string };
  price: number;
  mode: "in_person" | "online";
  escrow: boolean;
}

const usd = (v: number) => "$" + Math.round(v).toLocaleString("en-US");

/** Plain-text lines of the bill of sale, shared by the PDF and by tests. */
export function billOfSaleLines(d: BillOfSaleData): string[] {
  const v = d.vehicle;
  const desc = `${v.year} ${v.make} ${v.model}${v.trim ? ` ${v.trim}` : ""}`;
  return [
    `Date: ${d.date}`,
    `Reference: ${d.purchaseId}`,
    "",
    "VEHICLE",
    `Description: ${desc}`,
    `VIN: ${v.vin ?? "____________________"}`,
    `Odometer: ${v.miles.toLocaleString("en-US")} miles`,
    `Color: ${v.color ?? "____________"}`,
    "",
    "SELLER",
    `Name: ${d.seller.legalName || "____________________"}`,
    `Address: ${d.seller.address || "____________________"}`,
    `Phone: ${d.seller.phone || "____________"}   Email: ${d.seller.email || "____________"}`,
    "",
    "BUYER",
    `Name: ${d.buyer.legalName}`,
    `Address: ${d.buyer.address}`,
    `Phone: ${d.buyer.phone}   Email: ${d.buyer.email}`,
    "",
    "SALE",
    `Purchase price: ${usd(d.price)}`,
    `Payment: ${d.escrow ? "Through a licensed escrow service" : d.mode === "in_person" ? "In person" : "As agreed between the parties"}`,
    "",
    "TERMS",
    "The seller certifies that they are the legal owner of the vehicle described above, that it is",
    "free of all liens and encumbrances except as disclosed in writing, and that the odometer",
    "reading stated is the actual mileage to the best of their knowledge.",
    "The vehicle is sold as is, where is, with no warranty expressed or implied, except that the",
    "seller will deliver a properly assigned title.",
    "The buyer acknowledges inspecting the vehicle or having had the opportunity to do so.",
    "",
    "SIGNATURES",
    "Seller: _______________________________   Date: ____________",
    "",
    "Buyer:  _______________________________   Date: ____________",
    "",
    "Generated by UrCar from purchase request " +
      d.purchaseId +
      ". Check your state's requirements;",
    "some states require a notarized bill of sale or their own form.",
  ];
}

export async function renderBillOfSale(d: BillOfSaleData): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([612, 792]);
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const margin = 56;
  let y = 792 - margin;
  page.drawText("BILL OF SALE", { x: margin, y, size: 20, font: bold, color: rgb(0.1, 0.1, 0.1) });
  y -= 14;
  page.drawText("Motor vehicle", { x: margin, y, size: 10, font, color: rgb(0.4, 0.4, 0.4) });
  y -= 24;
  const headings = new Set(["VEHICLE", "SELLER", "BUYER", "SALE", "TERMS", "SIGNATURES"]);
  for (const line of billOfSaleLines(d)) {
    if (y < margin + 20) {
      y = 792 - margin;
      pdf.addPage([612, 792]);
    }
    const isHead = headings.has(line);
    page.drawText(line, {
      x: margin,
      y,
      size: isHead ? 11 : 10,
      font: isHead ? bold : font,
      color: rgb(0.1, 0.1, 0.1),
    });
    y -= isHead ? 16 : 14;
  }
  pdf.setTitle(`Bill of sale ${d.purchaseId}`);
  pdf.setProducer("UrCar");
  return pdf.save();
}
